# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Singularity Tutorial
author: Sylabs.io
logo: images/singularity-logo-round.svg

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Information about where the book exists on the web
repository:
  url: https://github.com/sylabs/singularity101  # Online location of your book
  path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  google_analytics_id: G-ZTE25XWQKF
  extra_footer: |
    <p>&copy; Copyright 2023</p>
    <p>Some parts of this course may have contents from the <a href="https://docs.sylabs.io/guides/latest/user-guide/">user guide</a> which are under BSD 3-Clause license.</p>
sphinx:
  config:
    html_show_copyright: false
    html_theme_options:
      use_download_button: false
      repository_url: https://github.com/sylabs/singularity101
      use_issues_button: true
      use_repository_button: true
      use_edit_page_button: true